"""Add hashed_password to Person

Revision ID: c857df88ebbd
Revises: 4f42ae364dfa
Create Date: 2026-02-12 19:15:02.037422

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c857df88ebbd'
down_revision: Union[str, Sequence[str], None] = '4f42ae364dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('staff', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'hashed_password')
    op.drop_column('staff', 'hashed_password')
    op.drop_column('parent', 'hashed_password')
    # ### end Alembic commands ###
